steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker-images/${REPO_NAME}', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker-images/${REPO_NAME}']
