steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker-images/${REPO_NAME}', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-west4-docker.pkg.dev/${PROJECT_ID}/docker-images/${REPO_NAME}']

  # Helm Package
  - name: 'gcr.io/${PROJECT_ID}/helm'
    args: ['package', 
           'helm']
    env:
    - 'SKIP_CLUSTER_CONFIG=true'

  # Helm Push
  - name: 'gcr.io/${PROJECT_ID}/helm'
    args: ['push', 
           '/workspace/ingress-merge-*.tgz', 'oci://europe-west4-docker.pkg.dev/${PROJECT_ID}/helm-charts']
    env:
    - 'SKIP_CLUSTER_CONFIG=true'